name: m5stack_core2
description: Useful functions for the M5Stack Core2.
dependencies:
  axp192:
    url: github.com/toitware/toit-axp192
    version: ^1.0.1
  color_tft:
    url: github.com/toitware/toit-color-tft
    version: ^1.3.1
  ft63xx:
    url: github.com/imliubo/ft63xx-toit
    version: ^1.0.1
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^1.7.1
