dependencies:
  axp192:
    url: github.com/toitware/toit-axp192
    version: ^1.0.1
  color_tft:
    url: github.com/toitware/toit-color-tft
    version: ^1.2.0
  m5stack_core2:
    path: ..
  pixel_display:
    url: github.com/toitware/toit-pixel-display
    version: ^1.6.0
